name: TRWM CI
on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:22-alpine

    steps:
      - name: Instalar git
        run: apk add --no-cache git

      - name: Permitir carpeta como 'safe.directory'
        run: git config --global --add safe.directory "${{ github.workspace }}"

      - uses: actions/checkout@v2

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar tests
        run: npm test

      - name: test report
        uses: dorny/test-reporter@v3
        if: ${{!cancelled()}}
        with:
          name: JEST report
          path: reports/junit/junit.xml
          reporter: jest-junit